In [1]:
import numpy as np

In [2]:
'''Exercise 1: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10'''

integer_array = np.arange(100,200,10)
integer_array.reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [8]:
'''Exercise 2: Following is the provided numPy array. return array of items in the third column from all rows
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])'''

sample_array = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
sample_array[0:,2]


array([33, 66, 99])

In [13]:
'''Exercise 3: Add the following two NumPy arrays and Modify a result array by calculating the square of each element
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
'''

array_1 = np.array([[5, 6, 9], [21 ,18, 27]])
array_2 = np.array([[15 ,33, 24], [4 ,7, 1]])
sum_array = array_1 + array_2
print(sum_array)
sqrt_array = np.square(sum_array)
print(sqrt_array)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]
